package com.edumerge.support.enums;

public enum ActivityType {
    TICKET_CREATED, ASSIGNED, REASSIGNED, STATUS_CHANGED, PRIORITY_CHANGED, 
    COMMENT_ADDED, INTERNAL_NOTE_ADDED, ESCALATED, SLA_BREACHED, RESOLVED, 
    REOPENED, CLOSED, STUDENT_RESPONDED, PENDING_REQUESTED
}
